apiVersion: v1
kind: Service
metadata:
  name: exercise1-service
spec:
  selector:
    app: exercise1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8080
  type: LoadBalancer

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: exercise1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exercise1
    spec:
      containers:
      - name: exercise1
        image: exercise1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080