apiVersion: v1
kind: Service
metadata:
  name: ex1-service
spec:
  selector:
    app: ex1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ex1
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: ex1
    spec:
      containers:
      - name: ex1
        image: ex1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
